export const CATEGORY_KEYWORDS = {
  'System Design': [
    'system design',
    'architecture',
    'scalability',
    'high availability',
    'fault tolerance',
    'clean architecture',
    'hexagonal',
    'onion',
    'modular monolith',
    'domain-driven design',
    'ddd',
  ],
  'Microservices & Distributed': [
    'microservice',
    'microservices',
    'distributed',
    'cap theorem',
    'pacelc',
    'consensus',
    'leader election',
    'partition tolerance',
    'service mesh',
    'sidecar pattern',
    'saga pattern',
  ],
  'Performance & Scaling': [
    'performance',
    'scaling',
    'load balancer',
    'optimization',
    'latency',
    'optimize',
    'caching',
    'cache',
    'redis',
    'distributed caching',
    'cdn',
  ],
  'API Design': [
    'api',
    'rest',
    'graphql',
    'api gateway',
    'api versioning',
    'idempotency',
    'messaging',
    'message queue',
    'pub-sub',
    'event stream',
    'asynchronous',
    'synchronous communication',
  ],
  Database: [
    'database',
    'sql',
    'nosql',
    'normalization',
    'denormalization',
    'transaction',
    'indexing',
    'sharding',
    'replication',
    'consistency',
    'acid',
    'base',
    'eventual consistency',
  ],
  'DevOps & Infrastructure': [
    'kubernetes',
    'docker',
    'infrastructure',
    'cicd',
    'chaos engineering',
    'containerization',
  ],
  'Security & Networking': [
    'security',
    'authentication',
    'auth',
    'jwt',
    'oauth',
    'sso',
    'session',
    'cookie',
    'network',
    'networking',
    'tcp',
    'http',
    'ipv4',
    'dns',
  ],
  'Code Quality': [
    'design pattern',
    'solid',
    'oop',
    'anti-pattern',
    'strategy pattern',
    'observer pattern',
    'clean code',
    'code quality',
    'coupling',
    'cohesion',
    'non-functional',
    'requirements',
    'reliability',
    'maintainability',
    'code',
  ],
  'Career & Engineering': [
    'career',
    'engineer',
    'resume',
    'job',
    'promotion',
    'junior',
    'senior',
    'staff',
    'netflix',
    'case study',
    'real-world',
    'production',
  ],
};
