export const CATEGORY_KEYWORDS = {
  'Software Architecture': [
    'architecture',
    'clean architecture',
    'hexagonal',
    'onion',
    'modular monolith',
  ],
  'Design Patterns': [
    'design pattern',
    'solid',
    'oop',
    'anti-pattern',
    'strategy pattern',
    'observer pattern',
  ],
  'System Design': [
    'system design',
    'scalability',
    'high availability',
    'fault tolerance',
  ],
  'Distributed Systems': [
    'distributed',
    'cap theorem',
    'pacelc',
    'consensus',
    'leader election',
    'partition tolerance',
  ],
  Microservices: [
    'microservice',
    'microservices',
    'service mesh',
    'sidecar pattern',
    'saga pattern',
  ],
  'Data Consistency': [
    'consistency',
    'eventual consistency',
    'acid',
    'base',
    'transaction',
  ],
  'Messaging & Communication': [
    'messaging',
    'message queue',
    'pub-sub',
    'event stream',
    'asynchronous',
    'synchronous communication',
  ],
  'API Design': [
    'api',
    'rest',
    'graphql',
    'api gateway',
    'api versioning',
    'idempotency',
  ],
  Database: [
    'database',
    'sql',
    'nosql',
    'indexing',
    'sharding',
    'replication',
    'normalization',
    'denormalization',
  ],
  Caching: ['cache', 'caching', 'redis', 'distributed caching', 'cdn'],
  'DevOps & Infrastructure': [
    'kubernetes',
    'docker',
    'infrastructure',
    'cicd',
    'chaos engineering',
    'containerization',
  ],
  'Performance & Scaling': [
    'performance',
    'scaling',
    'load balancer',
    'optimization',
    'latency',
    'optimize',
  ],
  Networking: ['network', 'networking', 'tcp', 'http', 'ipv4', 'dns'],
  'Security & Auth': [
    'security',
    'authentication',
    'auth',
    'jwt',
    'oauth',
    'sso',
    'session',
    'cookie',
  ],
  'Software Engineering': [
    'clean code',
    'code quality',
    'coupling',
    'cohesion',
    'domain-driven design',
    'ddd',
  ],
  'Non-Functional Requirements': [
    'non-functional',
    'requirements',
    'reliability',
    'maintainability',
  ],
  'Career Development': [
    'career',
    'engineer',
    'resume',
    'job',
    'promotion',
    'junior',
    'senior',
    'staff',
  ],
  'Case Studies': ['netflix', 'case study', 'real-world', 'production'],
};
